# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:

    docker:
      # choose the right version, which include the maven, otherwise the mvn deploy will fail
      - image: cimg/android:2023.02

    steps:
      - checkout

      #run mvn
      - run:
         name: run mvn
         command: |
            mvn clean install


      # run tests
      - run:
         name: run tests
         command: bash ./sync-endpoint-docker-test/init.sh
