# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:

    docker:
      # choose the right version, which include the maven, otherwise the mvn deploy will fail
      - image: cimg/openjdk:19.0.2

    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t s1y333/docker_testimage:${CIRCLE_SHA1} -f ./sync-endpoint-docker-test/Dockerfile .
      - run:
          name: Push Docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push s1y333/docker_testimage:${CIRCLE_SHA1}
      #run mvn
      - run: 
         name: mvn install
         command: mvn clean install 
  
  docker_test:
      docker:
        - image: cimg/openjdk:19.0.2
      steps:
        - checkout
        - run:
           name: run docker tests
           command: bash ./sync-endpoint-docker-test/init.sh

workflows: 
  build_and_deploy:
    jobs:
      - build
      - docker_test:
          requires:
            - build
     
