# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:

    docker:
      # choose the right version, which include the maven, otherwise the mvn deploy will fail
      - image: cimg/openjdk:19.0.2

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.9
      #get docker host info
      - run: 
          name: check docker image
          command: docker info
      #run mvn
      - run: 
         name: mvn install
         command: mvn clean install 
  
  docker_test:
      docker:
        - image: cimg/openjdk:19.0.2
      steps:
        - checkout
        - run:
           name: run docker tests
           command: bash ./sync-endpoint-docker-test/init.sh

workflows: 
  build_and_deploy:
    jobs:
      - build
      - docker_test:
          requires:
            - build
     
